export { Api } from "./tl";
import * as tl from "./tl";
export { TelegramClient } from "./client/TelegramClient";
export { Connection } from "./network";
export { version } from "./Version";
export { Logger } from "./extensions/Logger";
import * as utils from "./Utils";
import * as errors from "./errors";
import * as sessions from "./sessions";
import * as extensions from "./extensions";
import * as helpers from "./Helpers";
import * as client from "./client";
import * as password from "./Password";
export { utils, errors, sessions, extensions, helpers, tl, password, client };
export declare const installPremiumEmoji: any;
export declare const emoji: any;
export declare const premiumState: any;
export declare const inlineSend: any;
export declare const banner: any;
export declare const rich: any;
