export function emo(emoji: any): any;
export function emoCustom(id: any, fallback: any): any;
export function emoAlias(name: any): string;
export function emoSocial(name: any): string;
export function carStrip(): string;
export function faceBlock(): string;
export function resolveAliases(text: any): any;
export function aliasToFallback(text: any): any;
export function aliasInfo(name: any): any;
export function aliasListByGroup(): Map<any, any>;
export function emojiById(id: any): any;
export function upgrade(html: any): any;
export function nodes(teks: any): any;
export function blokPremium(blok: any): any;
export function strip(html: any): any;
export function plain(html: any): any;
export function unwrapPlain(html: any): any;
export function capCustom(html: any, max?: number): any;
export function ensure(html: any, marker?: string): any;
export function render(html: any, premium?: boolean): any;
export function countCustom(html: any): number;
export function hasCustom(html: any): boolean;
export const MAX_CUSTOM_EMOJI: 100;
export declare function aliasList(): {
    name: string;
    group: string;
    emoji: string;
    id: string;
    fallback: string;
}[];
